CREATE INDEX idx_nome1 ON suvinil (nome);
CREATE INDEX idx_red1 ON suvinil (red);
CREATE INDEX idx_green1 ON suvinil (green);
CREATE INDEX idx_blue1 ON suvinil (blue);
CREATE INDEX idx_hex1 ON suvinil (hexadecimal);
CREATE INDEX idx_ncs1 ON suvinil(ncs);
CREATE INDEX idx_codigo_suvinil1 ON suvinil(codigo_suvinil);
CREATE INDEX idx_pantone_cod1 ON suvinil (pantone_código);
CREATE INDEX idx_pantone_name1 ON suvinil (pantone_name);
CREATE INDEX idx_pantone_hex1 ON suvinil (pantone_hex);
CREATE INDEX idx_fornecedores1 ON suvinil (fornecedores);
CREATE INDEX idx_created_at1 ON suvinil(CREATED_AT);
CREATE INDEX idx_updated_at1 ON suvinil(UPDATED_AT);
CREATE INDEX idx_deleted_at1 ON suvinil(DELETED_AT);

CREATE INDEX idx_nome2 ON coral (nome);
CREATE INDEX idx_red2 ON coral (red);
CREATE INDEX idx_green2 ON coral (green);
CREATE INDEX idx_blue2 ON coral (blue);
CREATE INDEX idx_hex2 ON coral (hexadecimal);
CREATE INDEX idx_pantone_cod2 ON coral (pantone_código);
CREATE INDEX idx_pantone_name2 ON coral (pantone_name);
CREATE INDEX idx_pantone_hex2 ON coral (pantone_hex);
CREATE INDEX idx_fornecedores2 ON coral (fornecedores);
CREATE INDEX idx_created_at2 ON coral(CREATED_AT);
CREATE INDEX idx_updated_at2 ON coral(UPDATED_AT);
CREATE INDEX idx_deleted_at2 ON coral(DELETED_AT);

CREATE INDEX idx_nome3 ON sherwin_willians(nome);
CREATE INDEX idx_red3 ON sherwin_willians(red);
CREATE INDEX idx_green3 ON sherwin_willians(green);
CREATE INDEX idx_blue3 ON sherwin_willians(blue);
CREATE INDEX idx_hex3 ON sherwin_willians(hexadecimal);
CREATE INDEX idx_pantone_cod3 ON sherwin_willians(pantone_código);
CREATE INDEX idx_pantone_name3 ON sherwin_willians(pantone_name);
CREATE INDEX idx_pantone_hex3 ON sherwin_willians(pantone_hex);
CREATE INDEX idx_fornecedores3 ON sherwin_willians(fornecedores);
CREATE INDEX idx_created_at3 ON sherwin_willians(CREATED_AT);
CREATE INDEX idx_updated_at3 ON sherwin_willians(UPDATED_AT);
CREATE INDEX idx_deleted_at3 ON sherwin_willians(DELETED_AT);

CREATE INDEX idx_nome4 ON anjo(nome);
CREATE INDEX idx_red4 ON anjo(red);
CREATE INDEX idx_green4 ON anjo(green);
CREATE INDEX idx_blue4 ON anjo(blue);
CREATE INDEX idx_hex4 ON anjo(hexadecimal);
CREATE INDEX idx_pantone_cod4 ON anjo(pantone_código);
CREATE INDEX idx_pantone_name4 ON anjo(pantone_name);
CREATE INDEX idx_pantone_hex4 ON anjo(pantone_hex);
CREATE INDEX idx_fornecedores4 ON anjo(fornecedores);
CREATE INDEX idx_created_at4 ON anjo(CREATED_AT);
CREATE INDEX idx_updated_at4 ON anjo(UPDATED_AT);
CREATE INDEX idx_deleted_at4 ON anjo(DELETED_AT);