CREATE INDEX idx_nome1 ON suvinil (nome);
CREATE INDEX idx_red1 ON suvinil (red);
CREATE INDEX idx_green1 ON suvinil (green);
CREATE INDEX idx_blue1 ON suvinil (blue);
CREATE INDEX idx_hex1 ON suvinil (hexadecimal);
CREATE INDEX idx_ncs1 ON suvinil(ncs);
CREATE INDEX idx_codigo_suvinil1 ON suvinil(codigo_suvinil);
CREATE INDEX idx_pantone_cod1 ON suvinil (pantone_código);
CREATE INDEX idx_pantone_name1 ON suvinil (pantone_name);
CREATE INDEX idx_pantone_hex1 ON suvinil (pantone_hex);
CREATE INDEX idx_fornecedores1 ON suvinil (fornecedores);
CREATE INDEX idx_created_at1 ON suvinil(CREATED_AT);
CREATE INDEX idx_updated_at1 ON suvinil(UPDATED_AT);
CREATE INDEX idx_deleted_at1 ON suvinil(DELETED_AT);

CREATE INDEX idx_nome2 ON coral (nome);
CREATE INDEX idx_red2 ON coral (red);
CREATE INDEX idx_green2 ON coral (green);
CREATE INDEX idx_blue2 ON coral (blue);
CREATE INDEX idx_hex2 ON coral (hexadecimal);
CREATE INDEX idx_pantone_cod2 ON coral (pantone_código);
CREATE INDEX idx_pantone_name2 ON coral (pantone_name);
CREATE INDEX idx_pantone_hex2 ON coral (pantone_hex);
CREATE INDEX idx_fornecedores2 ON coral (fornecedores);
CREATE INDEX idx_created_at2 ON suvinil(CREATED_AT);
CREATE INDEX idx_updated_at2 ON suvinil(UPDATED_AT);
CREATE INDEX idx_deleted_at2 ON suvinil(DELETED_AT);
